version: "3.1"
services:

  # Persistence (postgresql)
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: diploma2022
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
