#@name simple PDF generation for testing purposes
POST http://localhost:8080/api/diploma/pdf/generate
Accept: application/octet-stream,application/pdf
Content-Type: application/json

{
  "requester": {
    "callSign": "oe5idt",
    "mail": "oe5idt@oevsv.at",
    "name": "David Schwingenschlögl"
  },
  "candidate": {
    "callSign": "oe5idt",
    "userID": "12345",
    "category": "S2S",
    "rank": "{{rank}}",
    "activations": {
      "OE1": 0,
      "OE2": 0,
      "OE3": 10,
      "OE4": 0,
      "OE5": 0,
      "OE6": 4,
      "OE7": 10,
      "OE8": 0,
      "OE9": 0
    }
  },
  "sequence": 737,
  "locale": "en-US",
  "quality": 0.1
}

>>! temporary/oe5idt_s2s_{{rank}}.pdf

###

#@name Fetch candidates
GET http://localhost:8080/api/diploma/candidates?callsign=OE5JFE
Accept: application/json

###

#@name Request sample diploma
POST http://localhost:8080/api/diploma/request?callsign=OE5JFE
Accept: application/json
Content-Type: application/json

{
  "requester": {
    "callSign": "OE5JFE",
    "mail": "oe5idt@oevsv.at",
    "name": "Dabbel Dabbel Wabbel"
  },
  "candidates": [
    {
      "candidate": {
        "callSign": "OE5JFE",
        "userID": "11330",
        "category": "ACTIVATOR",
        "rank": "GOLD",
        "activations": {
          "OE1": 1,
          "OE2": 21,
          "OE3": 11,
          "OE4": 1,
          "OE5": 223,
          "OE6": 43,
          "OE7": 6,
          "OE8": 7,
          "OE9": 1
        }
      },
      "signature": "59023ECD0F00D986B5351EB375675209CA0BD4CCFD4EE9E933054A2546D2BE1D"
    }
  ]
}

###

#@name Send test mail
POST http://localhost:8080/api/mail/test?to=oe5idt@oevsv.at&templated=true
Accept: application/json

###

#@name Synchronize summits
POST http://localhost:8080/api/summits/synchronize
Accept: application/json

###

#@name Checking ResourceBundle troubles
GET http://localhost:8080/api/test/bundle
Accept: text/plain
